### ISSUE TITLE
[Redshift] determining the number of temporary tables during merge

### ISSUE THREAD

**Issue by mjalkio** [embulk/embulk-output-jdbc#195]
Hello,

I've noticed that when I'm running Embulk locally that eight temporary tables get created during merge (`_bl_tmp000` through `_bl_tmp007`). However, when I run from my EC2 instance, only two temporary tables are created.

As of right now this isn't causing any issues, but I'd like to understand why this is happening. It seems that `taskCount` is the variable that sets this but I can't see where `taskCount` is set (I can trace it as far as `public ConfigDiff transaction`. Can you help out?

```
for (int taskIndex = 0; taskIndex < taskCount; taskIndex++) {
                            String tableName = namePrefix + String.format("%03d", taskIndex);
```

**Comment by sakama** [comment]
Hi.

`taskCount` and "each tasks" are set by Embulk itself and are't set by plugins.
In particular, Embulk executes each tasks at Executor and this is also a plugin(Executor plugin).
This task number is decided at Executor plugin.

I guess your local machine has 4 CPU cores so that taskCount became **4*2=8** and EC2 instance has 1 CPU cores and taskCount became **1*2=2**.
You can change this Executor's  number at `exec` section of config.yml.
http://www.embulk.org/docs/built-in.html#local-executor-plugin

This document also may help you. Original isn't a English, though.
https://translate.google.com/translate?sl=ja&tl=en&js=y&prev=_t&hl=ja&ie=UTF-8&u=http%3A%2F%2Fqiita.com%2Fsonots%2Fitems%2F4445467ddb5cea0622a5&edit-text=&act=url

**Comment by mjalkio** [comment]
Thank you!
