### ISSUE TITLE
SQL Server: Native Client have null character bug. [Sorry!]

### ISSUE THREAD

**Issue by kitsuyui** [embulk/embulk-output-jdbc#213]
I'm so sorry. I found that I've embeded terrible bug on my PR: https://github.com/embulk/embulk-output-jdbc/pull/209

Reusing pointer have been dirty.
[So I added this padding way.](https://github.com/kitsuyui/embulk-output-jdbc/blob/32a11a7f74cb933714c3fbf4c48784dc3c2712fd/embulk-output-sqlserver/src/main/java/org/embulk/output/sqlserver/nativeclient/NativeClientWrapper.java#L170-L175)
But it is insufficient for nvarchar.
It causes padded many null characters in nvarchar.
Other types seems to be no problem.

<img width="248" alt="null padded" src="https://user-images.githubusercontent.com/2596972/33004065-03d2f6e2-ce02-11e7-9dc9-a4b465792ddc.png">

**Comment by hito4t** [comment]
@kitsuyui 
Thank you for testing!

It is not good that existing JUnit test cases can't expose this issue.

`org.embulk.output.sqlserver.BasicTest#testNativeInsertDirect` uses the native client and has a NCARCHAR column.
But because the value of the second row in test data (test1.csv) is longer than the value of the first row, the test case can't expose the dirty pointer problem.
We should add the row whose value is shorter than the second row.
(I'll do it later.)
