### ISSUE TITLE
Columns dropped in output due to case problem

### ISSUE THREAD

**Issue by lance-edmodo** [embulk/embulk-output-jdbc#97]
There is a problem with copying columns that have upper-case characters in their names.

Here is the table DDL in MySQL:
CREATE TABLE `account_buyertransaction` (
  `id` int(11),
  `session_id` varchar(64),
  `referenceId` varchar(32),
  `paymentMerchant` varchar(32),
  `status` tinyint(1),
  `creation_date` datetime,
  `user_id` bigint(20),
  `payment_reason` longtext,
  `payment_reason_hash` longtext
) ;

Note that 'referenceId' and 'paymentMerchant' have upper-case characters in their names. Case is ignored in SQL column names. The matching table in Redshift (Postgres) has lower-case column names.

Here are the logs for an Embulk run. Notice that 'CREATE TABLE' has the two fields with lower-case names. Also, notice that the COPY command does not include the two fields- it only has the columns with all lower-case characters in their names.

2016-04-04 22:29:50.800 +0000 [INFO] (0001:transaction): SQL: DROP TABLE IF EXISTS "account_buy_33cbe340_bl_tmp002"
...
2016-04-04 22:29:51.413 +0000 [INFO] (0001:transaction): SQL: CREATE TABLE IF NOT EXISTS "account_buy_33cbe340_bl_tmp002" ("id" INT4, "session_id" VARCHAR(192), "referenceid" VARCHAR(96), "paymentmerchant" VARCHAR(96), "status" INT2, "creation_date" TIMESTAMP, "user_id" INT8, "payment_reason" VARCHAR(256), "payment_reason_hash" VARCHAR(256))
...
2016-04-04 22:29:53.443 +0000 [INFO] (0018:task-0000): Copy SQL: COPY "account_buy_33cbe340_bl_tmp002" ("id", "session_id", "status", "creation_date", "user_id", "payment_reason", "payment_reason_hash") ? GZIP DELIMITER '\t' NULL '\\N' ESCAPE TRUNCATECOLUMNS ACCEPTINVCHARS STATUPDATE OFF COMPUPDATE OFF

**Comment by hiroyuki-sato** [comment]
Hello @lance-edmodo 

I tested about Upper case columns on MySQL and PostgreSQL.
It works properly. 
https://gist.github.com/hiroyuki-sato/85c0b6dd12b20cd080a156d05750c963

Could you tell me more detail about your problem?.

* Embulk version
* Your embulk configuration
* Test data.

I needed quote uppper case columns when I create table before embulk load.

```sql
CREATE TABLE account_buyertransaction (
  id integer,
  session_id varchar(64),
  "referenceId" varchar(32),
  "paymentMerchant" varchar(32),
  status integer,
  creation_date timestamp,
  user_id bigint,
  payment_reason text,
  payment_reason_hash text
) ;
```

Otherwise, Postgresql convert columns name to  lower  like ``referenceid`` and ``paymentmerchant``.

**Comment by lance-edmodo** [comment]
I will try this.

But, SQL is supposed to be case-insensitive in respect to column. Upper- and lower-case letters are supposed to mean the same letter in column names. Therefore, external software which compares column names should also ignore case.

**Comment by hito4t** [comment]
I understand what you say, but that is not so easy problem.

Oracle and PostgreSQL distinguish between lowercase and uppercase if table names or column names are enclosed in quotations.
SQL Server also distinguishes between lowercase and uppercase dependent on collation precedence settings.

But I'll try to resolve this problem.

**Comment by hito4t** [comment]
My idea for implementation:
1. get all table names using `java.sql.DatabaseMetaDate#getTables`.
2. if specified table name exists in 1 (case-sensitive), that is actual table name.
3. Search table name from 1 (case-insensitive). If only one table name is found, that is actual table name. Otherwise error.
4. Do the same way for column names.

**Comment by lance-edmodo** [comment]
Wow, I see what you mean. It is hard to find a good answer based on the "Principle of Least Surprise".

**Comment by hito4t** [comment]
#108
